name: "Build"

on:
  pull_request:

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Make
        run: make build

      - name: Make Image
        run: make image